package com.miu.onlinemarketplace.common.enums;

public enum MailType {
    SIGNUP_VERIFICATION_CODE,
    FORGOT_PASSWORD_REQUEST_CODE,
    PASSWORD_CHANGE_NOTIFICATION,
    ACCOUNT_APPROVE_NOTIFICATION,
    ACCOUNT_SUSPEND_NOTIFICATION,
    ORDER_CONFIRMED_NOTIFICATION,
    ORDER_CANCELED_NOTIFICATION,
    ORDER_SHIPPED_NOTIFICATION,
    ORDER_DELIVERED_NOTIFICATION,
    PAYMENT_FAIL_NOTIFICATION,

    ORDER_PAY_NOTIFICATION
}
