spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pmdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

app:

  domainUrl: http://localhost:4200
  stripe:
    secret: ${STRIPE_SECRET_KEY}
  cors:
    allowed-origins:
      - http://localhost:4200
      - http://localhost:8080
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expire-seconds: 86400

minio:
  bucket:
    name: pmstorage
  access:
    key: ${MINIO_KEY}
    secret: ${MINIO_SECRET}
  url: http://127.0.0.1:9000

